name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false

    - name: set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12

    - name: Change wrapper permissions
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Generate Documentation
      run: ./gradlew dokka

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: app/build/dokka/app
        CLEAN: true # Automatically remove deleted files from the deploy branch